version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  sonarperl:
    image: otrosien/sonar-perl
    ports:
    - "9000:9000"
    networks:
      - prodnetwork
  sample:
    build: ./perl/sample-project
    networks:
      - prodnetwork
    environment:
      - SONAR_HOST_URL=http://host.docker.internal:9000
